-- PROCEDURE`s
CREATE OR REPLACE PROCEDURE P_CRIA_TAXA(
P_COD_TORNEIO IN NUMBER
)AS AUX NUMBER;

BEGIN
  SELECT COD_TIME INTO AUX FROM COBRANCA;
  SELECT P_MOSTRA_TIMES_TORNEIO(P_COD_TORNEIO) INTO AUX FROM DUAL;
  
  INSERT INTO COBRANCA VALUES(MAX(ID) + 1, SYSDATE, SYSDATE, P_COD_TORNEIO.VAL_INSCRICAO, AUX.COD_TIME);
  
END P_CRIA_TAXA;

create or replace PROCEDURE P_MOSTRA_TIMES_TORNEIO(
P_COD_TORNEIO IN NUMBER
)AS V_NOME TIME.NOM_TIME%TYPE;
CURSOR V_I IS SELECT COD_TORNEIO, COD_TIME FROM TORNEIO_TIME;
BEGIN
FOR I IN V_I LOOP
SELECT NOM_TIME INTO V_NOME FROM TIME T, TORNEIO_TIME TT WHERE TT.COD_TORNEIO = P_COD_TORNEIO
AND T.COD_TIME = I.COD_TIME
AND TT.COD_TIME = T.COD_TIME;
SYS.DBMS_OUTPUT.PUT_LINE('TIME '||V_NOME||' TORNEIO '||P_COD_TORNEIO);
END LOOP;
END P_MOSTRA_TIMES_TORNEIO;


create or replace PROCEDURE P_GERA_TORNEIO(
P_COD_TORNEIO IN NUMBER,
P_DES_TORNEIO IN VARCHAR2,
P_VAL_INSCRICAO IN NUMBER,
P_IND_SERIE IN VARCHAR2
)AS V_COD_TIME TORNEIO_TIME.COD_TIME%TYPE;
CURSOR V_QLQR_NOME IS SELECT COD_TIME FROM TIME WHERE IND_SERIE = P_IND_SERIE;
BEGIN
  INSERT INTO TORNEIO VALUES (P_COD_TORNEIO, P_DES_TORNEIO, P_VAL_INSCRICAO);
  
  FOR I IN V_QLQR_NOME LOOP
  
  INSERT INTO TORNEIO_TIME VALUES(P_COD_TORNEIO, I.COD_TIME);
  
  END LOOP;
END P_GERA_TORNEIO;


-- FUNCTION
create or replace FUNCTION F_NOME_TIME(
C_TIME IN NUMBER
)RETURN VARCHAR2 AS AUX_NAME VARCHAR2(30); 
BEGIN
  SELECT NOM_TIME INTO AUX_NAME FROM TIME WHERE C_TIME = COD_TIME;
  RETURN AUX_NAME;
END F_NOME_TIME;

-- TESTE PROCEDURE
EXECUTE P_GERA_TORNEIO(0, 'TORNEIO TESTE', 10, 'D');


-- SELECTS
SELECT * FROM TORNEIO;
SELECT * FROM TORNEIO_TIME;
SELECT * FROM TIME;
SELECT * FROM COBRANCA;

-- DESC
DESC TIME;
DESC COBRANCA;
DESC TORNEIO;
DESC TORNEIO_TIME;


-- INSERTS
INSERT INTO TIME VALUES(0, 'FA', 'D');
INSERT INTO TIME VALUES(1, 'FB', 'D');
INSERT INTO TIME VALUES(2, 'FC', 'D');
INSERT INTO TIME VALUES(3, 'FD', 'D');
INSERT INTO TIME VALUES(4, 'FE', 'D');
INSERT INTO TIME VALUES(5, 'FF', 'D');
INSERT INTO TIME VALUES(6, 'FG', 'D');
INSERT INTO TIME VALUES(7, 'FH', 'E');
INSERT INTO TIME VALUES(8, 'FI', 'E');

-- ALTER TABLE
ALTER TABLE TORNEIO ADD CONSTRAINT PK_COD_TORNEIO PRIMARY KEY (COD_TORNEIO);
ALTER TABLE TIME ADD CONSTRAINT PK_COD_TIME PRIMARY KEY (COD_TIME);
ALTER TABLE TORNEIO_TIME ADD CONSTRAINT FK_COD_TORNEIO FOREIGN KEY (COD_TORNEIO) REFERENCES TORNEIO (COD_TORNEIO);
ALTER TABLE TORNEIO_TIME ADD CONSTRAINT FK_COD_TIME FOREIGN KEY (COD_TIME) REFERENCES TIME (COD_TIME);

-- PK
ALTER TABLE COBRANCA ADD CONSTRAINT PK_ID PRIMARY KEY (ID);
-- EXAMPLE
ALTER TABLE table_name
ADD CONSTRAINT constraint_name PRIMARY KEY (column1, column2, ... column_n);
-- PK
ALTER TABLE COBRANCA ADD CONSTRAINT FK_COBRANCA_COD_TIME FOREIGN KEY (COD_TIME) REFERENCES TIME (COD_TIME);

ALTER TABLE TORNEIO
DROP CONSTRAINT PK_COD_TIME;

-- SALVAR E PERMANCER
COMMIT;